//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""BallFight"",
            ""id"": ""7e66dcfc-43b7-4b08-860d-982aadeadc34"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""675cbe7d-75ca-4158-933b-c7fa2b143848"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PivotRotation"",
                    ""type"": ""Value"",
                    ""id"": ""2a9c8bf8-5161-40e9-bdf5-19506b2d82e5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraDistance"",
                    ""type"": ""Value"",
                    ""id"": ""e3feaf36-966a-4fbe-a081-742e705892ae"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""ede2e62c-eec1-4067-bcd7-f192c778d524"",
                    ""path"": ""3DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""239a2c6c-6b8d-4f2f-a6c0-f2a58a08f194"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b86a26ac-4d45-4474-aea7-0e92bf33d104"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""bd6eca77-af64-4e23-82ba-8c80c34c727e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c54749b3-f59a-4a31-8785-429750d167ba"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""883d208b-feeb-4d70-98d0-f3f438ec9ee9"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""08d85f16-20b9-4a4b-a561-fde01cb54071"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""51a0f759-c752-4ab5-a674-0dd8b56f0b00"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraDistance"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""77678f79-0791-4838-9e44-44cb7913e048"",
                    ""path"": ""<Mouse>/scroll/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraDistance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cab432e0-3683-4d44-8718-3840fdfd21fc"",
                    ""path"": ""<Mouse>/scroll/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraDistance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c4413c75-acab-4f64-91bf-e4aed078eb13"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PivotRotation"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""51fe41a9-f0e7-46b4-b654-affb832ce649"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PivotRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4bb52c3b-8766-44b8-85c1-142eb03d10ca"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PivotRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""144b52e3-2a33-4a0d-b7e1-73ab21c44b6c"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PivotRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ba780944-0f2d-435e-8258-3d2eb6c25612"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PivotRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BallFight
        m_BallFight = asset.FindActionMap("BallFight", throwIfNotFound: true);
        m_BallFight_Move = m_BallFight.FindAction("Move", throwIfNotFound: true);
        m_BallFight_PivotRotation = m_BallFight.FindAction("PivotRotation", throwIfNotFound: true);
        m_BallFight_CameraDistance = m_BallFight.FindAction("CameraDistance", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BallFight
    private readonly InputActionMap m_BallFight;
    private List<IBallFightActions> m_BallFightActionsCallbackInterfaces = new List<IBallFightActions>();
    private readonly InputAction m_BallFight_Move;
    private readonly InputAction m_BallFight_PivotRotation;
    private readonly InputAction m_BallFight_CameraDistance;
    public struct BallFightActions
    {
        private @InputActions m_Wrapper;
        public BallFightActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_BallFight_Move;
        public InputAction @PivotRotation => m_Wrapper.m_BallFight_PivotRotation;
        public InputAction @CameraDistance => m_Wrapper.m_BallFight_CameraDistance;
        public InputActionMap Get() { return m_Wrapper.m_BallFight; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BallFightActions set) { return set.Get(); }
        public void AddCallbacks(IBallFightActions instance)
        {
            if (instance == null || m_Wrapper.m_BallFightActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BallFightActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @PivotRotation.started += instance.OnPivotRotation;
            @PivotRotation.performed += instance.OnPivotRotation;
            @PivotRotation.canceled += instance.OnPivotRotation;
            @CameraDistance.started += instance.OnCameraDistance;
            @CameraDistance.performed += instance.OnCameraDistance;
            @CameraDistance.canceled += instance.OnCameraDistance;
        }

        private void UnregisterCallbacks(IBallFightActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @PivotRotation.started -= instance.OnPivotRotation;
            @PivotRotation.performed -= instance.OnPivotRotation;
            @PivotRotation.canceled -= instance.OnPivotRotation;
            @CameraDistance.started -= instance.OnCameraDistance;
            @CameraDistance.performed -= instance.OnCameraDistance;
            @CameraDistance.canceled -= instance.OnCameraDistance;
        }

        public void RemoveCallbacks(IBallFightActions instance)
        {
            if (m_Wrapper.m_BallFightActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBallFightActions instance)
        {
            foreach (var item in m_Wrapper.m_BallFightActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BallFightActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BallFightActions @BallFight => new BallFightActions(this);
    public interface IBallFightActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnPivotRotation(InputAction.CallbackContext context);
        void OnCameraDistance(InputAction.CallbackContext context);
    }
}
